### PR TITLE
More SEO title, Don't run on unnecessary sites.

### PR DESCRIPTION
**Pull request by BrockA**

### CODE REVIEW

**Comment by BrockA** [comment]
Approved but not merged?

**Comment by makyen** [comment]
While I agree that a more descriptive `@name` is desirable, changing the `@name` (or `@namespace`) can cause the userscript to not be automatically updated by userscript managers. Thus, making this change may cause users to be stuck on the older version until such time as they update manually. In addition, IIRC, users will not be informed, in any way, that there's a potential new version available.

Frankly, it's been quite a while since I tested this behavior on the various userscript managers, so it's possible that the upgrade functionality has changed.

If there really is a desire to change the `@name`, I'd suggest implementing an intermediate version that prompts the user to update when a new version is detected by the script. Then give at least several days (a couple weeks would be better) with the intermediate version as the released version. That time will give most users the chance to have the version updated automatically by their userscript manager to the intermediate version. Once the intermediate version is installed for all (or at least most) users, you can push a version with the `@name` changed to GitHub. The intermediate version will then detect it and prompt the user to go to the download URL to manually download the upgrade.

**Comment by Glorfindel83** [comment]
@BrockA sorry, I somehow thought that was automatic.
@makyen thanks for explaining this behaviour in detail, I didn't know this before. Since it's a brand new script with (estimated) no more than half a dozen installs, it's probably fine this time.

**Comment by BrockA** [comment]
Thanks, @Glorfindel83 .

@makyen , There is no such name check for either Tampermonkey or Violentmonkey.  There wasn't one either for Greasemonkey, but after GM4, I don't care enough to (re)check.

Update testing can be tricky due to caching and, for some engines, not reporting actual updates due to the update interval in settings not having passed.

**Pull request merged**
