### PR TITLE
Restrict button for revisions to show approriately

### PR DESCRIPTION
**Pull request by PurpleMagick**
If any link on the page ends in `/view-source` then the "Detect OpenAI" button shows up.

Instead now matching links in the top section of a revision markup.

---

See report here: https://stackapps.com/a/9637

The indiscriminate match of links that end in `view-source` was over-eager. It should now match only if a revision is shown. The markup makes it inconvenient to match for "Link button in the heading of a revision" but I think the selector chosen is adequate. It gets the first div in an element with a class "js-revision". 

Here is the structure of the HTML for the revisions page for reference: 

```html
<div class="js-revisions">
 <!-- omitted -->
  <div class="mb12 js-revision">
    <div class="d-flex p4 ai-center gs4 bg-powder-100">
      <div class="flex--item">
        <button type="button" class="s-btn s-btn__unset c-pointer js-revision-expander" data-controller="s-expandable-control" aria-expanded="true" aria-controls="rev-body-00000000-0000-0000-0000-000000000000" data-guid="00000000-0000-0000-0000-000000000000" data-is-loaded="true">
          <div class="d-flex ai-center py8 gs8 gsx fc-black-600 md:fd-column-reverse">
            <div class="flex--item">
              <svg aria-hidden="true" class="js-off-icon d-none svg-icon iconArrowRightAlt" width="18" height="18" viewBox="0 0 18 18">
                <path d="M6.41 2 5 3.41 10.59 9 5 14.59 6.41 16l7-7-7-7Z"></path>
              </svg>
              <svg aria-hidden="true" class="js-on-icon svg-icon iconArrowDownAlt" width="18" height="18" viewBox="0 0 18 18">
                <path d="m16.01 7.43-1.4-1.41L9 11.6 3.42 6l-1.4 1.42 7 7 7-7Z"></path>
              </svg>
            </div>
            <div class="flex--item w48 fs-headline1 fw-bold ta-left md:ta-center" title="revision 1">1</div>
          </div>
        </button>
      </div>
      <div class="flex--item fl1 wmn1">
        <div class="d-flex ai-center fw-wrap">
          <div class="flex--item">
            <span class="js-revision-comment"></span>
          </div>
        </div>
        <div class="d-flex gs8 s-anchors s-anchors__muted fw-wrap pt8">
          <a href="/revisions/00000000-0000-0000-0000-000000000000/view-source" class="flex--item" title="view raw text of this revision" target="_blank">Source</a>
          <a href="/revisions/0000/1" class="flex--item" title="link to this formatted revision">Link</a>
          <button type="button" class="flex--item s-btn s-btn__link js-full-link d-none">
            Full
          </button>
        </div>
        <div class="d-none md:d-block mt8">
          <!-- user details - omitted-->
        </div>
      </div>
	  <!-- other details - omitted-->
     </div>
    <div id="rev-body-00000000-0000-0000-0000-000000000000" class="s-expandable is-expanded" style="clip-path: none !important;">
      <!-- body of the post - omitted-->
	</div>
  </div>
</div>
```

An alternative to matching the exact elements would be to watch out for which page it is and load or not load the code, however, that might still be brittle if a body of a post happens to include a link which ends in `/view-source`. Also, I am not entirely sure if there are other pages where revisions are shown. If so, this code should work on them as well, without requiring explicit whitelisting. As long as the HTML structure matches what looks like a revision, the button will be added.

### CODE REVIEW

**Comment by makyen** [comment]
Note: the [bug report](https://stackapps.com/a/9637/29529) states that the button isn't functional on [the comment](https://anime.stackexchange.com/questions/62448/can-luffys-cut-wounds-seal-like-rubber#comment80490_67644). At least for me, that button is fully functional.

Having the button on the comment is, of course, unintended and the formatting could be better. On the other hand, I could certainly see how having a button next to the view-source link (in comments and posts) could be useful. However, if that is desired, it would be better for both the link to be more accurately determined to be a valid SE view-source link, rather than *just* the `href` ending in "/view-source"; and the formatting/placement to be much more clear what the "Detect OpenAI" link is associated with. For example:

> You can prepend a paragraph with `>!` (like [this](https://anime.stackexchange.com/revisions/38359734-a20f-4a93-8e57-4a5997ee8ca1/view-source) (Detect OpenAI)) to add a spoiler block, but it only works on questions and answers, not comments :) – Aki Tanaka♦ [Jan 13 at 15:16](https://anime.stackexchange.com/questions/62448/can-luffys-cut-wounds-seal-like-rubber#comment80490_67644)

BTW: The "Detect OpenAI" button on the revisions page should be a `<button>`, not a `<a>`. I'll submit a PR which makes that change shortly. I'll change the `version` in that, as I note you didn't do so in this PR. Then, if that's merged after this, we'll have a version bump.

I don't have a problem with going ahead and merging this and deciding later to have or not have the functionality of also adding "Detect OpenAI" links on "/view-source" links on other pages.

**Comment by PurpleMagick** [comment]
> The "Detect OpenAI" button on the revisions page should be a <button>, not a <a>

I followed the other buttons which were also `<a>` tags. However, I do not mind at all if it's made a `<button>` - it will be more consistent anyway.

As for potentially making the button show for any link to a revision - unintended but as you say, it might be useful. My only concern is cluttering the UI. It might be worth introducing configuration for whether the users want to attach the button to all revision links (outside revisions page) or not. Might be worth discussing this at a later point, though.

**Comment by PurpleMagick** [comment]
Also - updated the script version to 0.8.1. I don't know if such granular versions are useful but it's a minor change IMO.

**Comment by PurpleMagick** [comment]
\*facepalm\* oops, I see you already had a PR with an updated version. My apologies.

**Comment by makyen** [comment]
Yeah, I can understand using an `<a>` there, given that all the other buttons in the revisions page interface for non-moderators are `<a>`, but all of them are actual links to new pages. For moderators, there's an actual `<button>`  added to the list of buttons there (which is from where I copied the HTML). In the past, SE hasn't been all that consistent about using `<a>` vs `<button>` semantically for buttons/links, but they have gotten more consistent over time.

I had two issues with using an `<a>` there, both of which could have been solved with preventing the default action in the event handler, but, upon reflection, using a `<button>` seemed a better alternative:
* The revisions page jumped to the top of the page when any "Detect OpenAI" button was pressed.
* The color of the `<a>` used for the "Detect OpenAI" button changed for all of the buttons to the `:visited` color when one of the buttons was pressed.


##### As to the `version`:
My personal preference is for [Semantic versioning](https://semver.org/).

Yes, one of the reasons I'd created another PR was to update the version number and it looked like it would be slightly easier given that you hadn't updated it here, but it's normal/expected that you update the `version` in your change<sup>1</sup> and will result in only a relatively minor merge conflict.

-----

1. If the `version` should be updated in the PR or if the repository maintainer wants to have control of it will vary from repository to repository. I don't recall it actually being specified for this repository. Usually, it's helpful for it to be updated. Sometimes it being updated is a minor inconvenience (typically when there's more than one PR open at a time). On rare occasions, it's bit of a pain in the rear, but that's usually only when a PR is substantially delayed wrt. being merged, or the person submitting the PR has a substantially different opinion as to what the version should be vs. what the maintainer feels it should be. For the times when it's a pain in the rear, it's possible to create a new branch in the main repository, merge the PR into that, modify things there, and then merge/cherry-pick that into the master branch. Making that easier is one of the reasons I habitually make the version change as a separate commit.

**Pull request merged**
